---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
bibliography: references.bib
cls: ecology.csl
---

## Preparación de datos 
- En este [script](preparaDatos.html) partimos de los datos originales de COPLAS desde 1992-2019 y generamos un data.frame "limpio" (corrección de errores), con la elevación y la especie de pino. Este dataset se guarda en `/data/coplas2019.csv`.

- Para el análisis de los datos de Sierra Nevada, vamos a generar un buffer de diferentes distancias para ver que parcelas elegimos. El proceso puede verse [aquí](bufferSN.html). Hemos cogido un buffer de 20 km y hemos añadido algunas parcelas (de Motril), y hemos eliminado algunas de Sierra Alhamilla. Los datos están en: `/data/coplas2019sn.csv`.

## Exploración del patrón temporal 
- Vamos a explorar el patrón temporal de los niveles de infestación medios por año, agrupados por grupo de elevación y por especie. 
- Nos quedamos con la agrupación por especie. Seleccionamos 4 especies (*P. nigra*, *P. halepensis*, *P. sylvestris*, *P. pinaster*)
- Los resultados pueden verse [aquí](evolucionTemporal.html)

## Análisis de Mann-Kendall
- Analizmos las [tendencias temporales](computeMannKendall.html) para cada parcela utilizando el test no paramétrico de Mann-Kendall.

## Análisis de Disparidad de las series de datos 
- Disparidad entre los valores de infestación entre años para cada parcela
- Variabilidad para cada serie de datos (cada parcela)
- Resultados [aquí](computeDisparity.html)
- Mas información sobre estos índices:  [@FernandezMartinezetal2018ConsecutiveDisparity; @FernandezMartinezPenuelas2021MeasuringTemporal; @HeathBorowski2013QuantifyingProportional]


## Relación nivel de infestación con la NAO

- Re-visitamos el trabajo de @Hodaretal2012ClimateChange, y volvemos a explorar la relación entre la NAO y el % de parcelas con nivel de infestacion >= 3. 
- Análisis exploratorio [aquí](dataNAO.html)  

# Referencias 
